eureka:
  ssl: true
  host: <discovery-service-host>
  port: <discovery-service-port>
  servicePath: '/eureka'
instance:
  app: manipulator-service
  vipAddress: manipulator-service
  hostName: <service-host>
  port: 5010
  securePort: 5010
  statusPageUrl: https://<service-host>:5010/application/info
  healthCheckUrl: https://<service-host>:5010/application/health
  metadata:
    apiml.catalog.tile.id: 'manipulator'
    apiml.catalog.tile.title: 'Mainframe Data Manipulator'
    apiml.catalog.tile.description: 'Service for manipulating mainframe data'
    apiml.routes.api_v1.gatewayUrl: "api/v1"
    apiml.routes.api_v1.serviceUrl: "/"
ssl:
  certificate: ssl/server.cer
  keystore: ssl/server.key
  caFile: ssl/ca.pem
